### ISSUE TITLE
Add link to auxiliary libraries

### ISSUE THREAD

**Issue by yilinwei** [talex5/ocaml-wayland#35]
Hi,

I've been using this library for something (luckily it doesn't need the GPU) so I've got quite a few helper libraries which I'm splitting out such as `xcursor` and `xkb`. Do you think it would be worthwhile to add some links on the README to the examples?

https://github.com/yilinwei/ocaml-xcursor/blob/main/example/wayland_example.ml

**Comment by talex5** [comment]
If you release your library to opam-repository with a dependency (even just a test one) on `wayland`, it will show up automatically at https://opam.ocaml.org/packages/wayland/

That way I don't have to keep any lists up-to-date :-)
