### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by alyssais** [talex5/ocaml-wayland#42]
Unless we switch off the release version of ocaml-wayland, we can't upgrade wayland-proxy-virtwl in Nixpkgs past https://github.com/talex5/wayland-proxy-virtwl/commit/ec052fa, because of the new protocols that are introduced after that.

**Comment by talex5** [comment]
OK, I updated the protocols and made a new release (https://github.com/ocaml/opam-repository/pull/25631).

However, if you clone the proxy with git submodules enabled then it should just work anyway.

**Comment by alyssais** [comment]
Generally we don't want multiple / vendored / non-release versions of libraries if we can avoid it.

**Comment by alyssais** [comment]
Thanks!
